diplonautic_landing_homepage:
    path:     /
    defaults: { _controller: DiplonauticLandingBundle:Default:index }

diplonautic_landing_about: 
    path:     /about
    defaults: { _controller: DiplonauticLandingBundle:Default:about }

diplonautic_landing_privacy_policy: 
    path:     /privacy-policy
    defaults: { _controller: DiplonauticLandingBundle:Default:privacyPolicy }

diplonautic_landing_data_protection: 
    path:     /data-protection
    defaults: { _controller: DiplonauticLandingBundle:Default:dataProtection }

diplonautic_landing_cookies: 
    path:     /cookies
    defaults: { _controller: DiplonauticLandingBundle:Default:cookies }
    
diplonautic_landing_contact: 
    path:     /contact
    defaults: { _controller: DiplonauticLandingBundle:Default:contact }    
    
diplonautic_landing_products: 
    path:     /products
    defaults: { _controller: DiplonauticLandingBundle:Default:products } 
    
diplonautic_landing_air_conditioner: 
    path:     /products/air-conditioner
    defaults: { _controller: DiplonauticLandingBundle:Default:airConditioner } 

diplonautic_landing_refrigeration_systems: 
    path:     /products/refrigeration-systems
    defaults: { _controller: DiplonauticLandingBundle:Default:refrigerationSystems }
    
diplonautic_landing_generators: 
    path:     /products/generators
    defaults: { _controller: DiplonauticLandingBundle:Default:generators }
    
diplonautic_landing_water_treatment: 
    path:     /products/water-treatment
    defaults: { _controller: DiplonauticLandingBundle:Default:waterTreatment } 

diplonautic_landing_electric_systems: 
    path:     /products/electric-systems
    defaults: { _controller: DiplonauticLandingBundle:Default:electricSystems } 
    
diplonautic_landing_maneuvering_propeller: 
    path:     /products/maneuvering-propeller
    defaults: { _controller: DiplonauticLandingBundle:Default:maneuveringPropeller }  
    
diplonautic_landing_opportunities: 
    path:     /opportunities
    defaults: { _controller: DiplonauticLandingBundle:Default:opportunities }        